version: '3.4'

services:
  aspnetcoregrpcservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5009:80"
      - "5010:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  workerservicegrpcservice:
    environment:
      - PORT=5011
    ports:
      - "5011:5011"
  consolegrpcclient:
    environment:
      - Grpc_ServicePort=81