version: '3.4'

services:
  aspnetcoregrpcservice:
    image: aspnetcoregrpcservice:dev
    container_name: AspNetCoreGrpcService
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AspNetCoreGrpcService"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_aspnetcoregrpcservice$
    volumes:
      - E:\mystudys\Net6GrpcServiceDemo\AspNetCoreGrpcService:/app
      - E:\mystudys\Net6GrpcServiceDemo:/src
      - C:\Users\mumu\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_aspnetcoregrpcservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_aspnetcoregrpcservice$ \"/app/bin/Debug/net6.0/AspNetCoreGrpcService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  workerservicegrpcservice:
    image: workerservicegrpcservice:dev
    container_name: WorkerServiceGrpcService
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WorkerServiceGrpcService"
    #environment:
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_workerservicegrpcservice$
    volumes:
      - E:\mystudys\Net6GrpcServiceDemo\WorkerServiceGrpcService:/app
      - C:\Users\mumu\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_workerservicegrpcservice$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_workerservicegrpcservice$ \"/app/bin/Debug/net6.0/WorkerServiceGrpcService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
